language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 10
  - 12
  - 14
before_script:
script:
  - npm run test
after_success:
install:
  - npm install
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
